[project]
name = "kas-plugin-helloworld"
description = "Example plugin for kas"
keywords = [ "kas" ]
license = { text = "MIT" }

dynamic = [ "version" ]
dependencies = [
 "kas >= 4.8.0",
 'pydantic'
]

[project.entry-points.'kas.plugins']
helloworld = 'kas_plugin_helloworld'

[tool.setuptools.package-data]
extended_data = ["extended-data.yml"]
